;;; somt utilities
(in-package #:cl-atproto-drisl)

(defun hash-table-keys (table)
  (let ((keys '()))
    (maphash (lambda (k v)
               (declare (ignore v))
               (push k keys))
             table)
    keys))

(defun integer-to-octets (n)
  (let* ((n-bytes (cbor-uint-bytes n))
         (out (make-array n-bytes :element-type '(unsigned-byte 8))))
    (loop for i from (1- n-bytes) downto 0
          for shift from 0 by 8
          do (setf (aref out i) (logand (ash n (- shift)) #xff)))
    out))

(defun base64-encode (octets)
  (let* ((table "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/")
         (len (length octets))
         (out (make-string (* 4 (ceiling len 3)))))
    (loop for i from 0 below len by 3
          for j from 0 by 4
          for b0 = (aref octets i)
          for b1 = (if (< (1+ i) len) (aref octets (1+ i)) 0)
          for b2 = (if (< (+ i 2) len) (aref octets (+ i 2)) 0)
          do (setf (aref out j)       (aref table (ash b0 -2))
                   (aref out (+ j 1)) (aref table (logior (ash (logand b0 3) 4) (ash b1 -4)))
                   (aref out (+ j 2)) (if (< (1+ i) len)
                                          (aref table (logior (ash (logand b1 15) 2) (ash b2 -6)))
                                          #\=)
                   (aref out (+ j 3)) (if (< (+ i 2) len)
                                          (aref table (logand b2 63))
                                          #\=)))
    out))


(defun base64-decode (string)
  (let* ((table "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/")
         (len (length string))
         (out-len (* 3 (floor len 4)))
         (padding (cond
                    ((and (> len 0) (char= (aref string (- len 1)) #\=))
                     (if (and (> len 1)
                              (char= (aref string (- len 2)) #\=))
                         2
                         1))
                    (t 0)))
         (out (make-array (- out-len padding)
                          :element-type '(unsigned-byte 8))))
    (labels ((value (c)
               (let ((pos (position c table)))
                 (or pos
                     (error "Invalid base64 character: ~C" c)))))
      (loop for i from 0 below len by 4
            for j from 0 by 3
            for c0 = (aref string i)
            for c1 = (aref string (+ i 1))
            for c2 = (if (< (+ i 2) len)
                         (aref string (+ i 2))
                         #\=)
            for c3 = (if (< (+ i 3) len)
                         (aref string (+ i 3))
                         #\=)
            for v0 = (value c0)
            for v1 = (value c1)
            for v2 = (if (char= c2 #\=) 0 (value c2))
            for v3 = (if (char= c3 #\=) 0 (value c3))
            for b0 = (logior (ash v0 2) (ash v1 -4))
            for b1 = (logior (ash (logand v1 15) 4) (ash v2 -2))
            for b2 = (logior (ash (logand v2 3) 6) v3)
            do (when (< j (length out))
                 (setf (aref out j) b0))
               (when (< (+ j 1) (length out))
                 (setf (aref out (+ j 1)) b1))
               (when (< (+ j 2) (length out))
                 (setf (aref out (+ j 2)) b2))))
    out))
